### PR TITLE
[Azure] Add sovereign cloud support for Storage

### LINKED ISSUE #861: [Azure] Add sovereign cloud support for storage
The Base URI is incorrectly resolved for the storage client, and should be fixed to read from the environment.

Addresses #811

### PR DESCRIPTION
**Pull request by davidkpiano**
This PR resolves the Base URI for the Resource Group module to support sovereign cloud.

Addresses #811, fixes #861 

cc. @rguthriemsft

### CODE REVIEW

**Comment by hattan** [comment]
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/745238923

File: modules/azure/storage.go [hunk 1]
```diff
@@ -191,6 +192,7 @@ func GetStorageAccountClientE(subscriptionID string) (*storage.AccountsClient, e
 }
 
 // GetStorageBlobContainerClientE creates a storage container client.
```
Comment (HadwaAbdelhalem) [inline modules/azure/storage.go:194]: remove the method GetStorageBlobContainerClientE  as it is no longer used

File: modules/azure/storage.go [hunk 2]
```diff
@@ -174,6 +174,7 @@ func GetStorageAccountPropertyE(storageAccountName, resourceGroupName, subscript
 }
 
 // GetStorageAccountClientE creates a storage account client.
+// TODO: remove in next version
```
Comment (HadwaAbdelhalem) [inline modules/azure/storage.go:177]: remove GetStorageAccountClientE method as it is no longer used

**Review by HadwaAbdelhalem — CHANGES_REQUESTED** [review]
Thanks @davidkpiano , one last NIT change

File: modules/azure/storage.go (hunk 1 above)
Comment (yorinasub17) [reply modules/azure/storage.go:194]: I mentioned this somewhere, but I can't find where I said this, so reiterating it here:

Since this is a public method, removing it means we will have to cut a backwards incompatible release. It would be a bit of a pain for us to release a backwards incompatible release for each of these changes. I think it would be better to keep these in so that we can merge all of these changes as patch releases, and then at the very end once all the files are updated, we can have one big PR to remove all the `Get.*Client` functions and cut one backwards incompatible release.

**Review by HadwaAbdelhalem — APPROVED** [review]

File: modules/azure/storage.go (hunk 1 above)
Comment (HadwaAbdelhalem) [reply modules/azure/storage.go:194]: sounds good @yorinasub17 , I approved it and it is ready for  review  @gruntwork-terratest-terragrunt

**Review by yorinasub17 — APPROVED** [review]
LGTM as well! Going to merge and release this version.
