### PR TITLE
Check if folder exists before attempting to copy folders

### LINKED ISSUE #738: test_structure.CopyTerraformFolderToTemp - verify terraformModuleFolder exists
test_structure.CopyTerraformFolderToTemp doesn't currently validate that directories passed into the function exist.

If the terraformModuleFolder directory that is passed into `test_structure.CopyTerraformFolderToTemp` doesn't exist, the failure is handled during the `terraform init` (i.e `Error: No configuration files`).

It might be better to fail earlier if the directory doesn't exist and report a detailed error message to make debugging easier.

Let me know if this seems like a good idea and I can attempt to whip up PR one of these days!

### PR DESCRIPTION
**Pull request by cbuto**
This PR attempts to close #738.

I ran through the unit tests that were affected by these changes. I'm not sure if the output is super useful for those but I also ran some of the automated tests that use `CopyTerraformFolderToTemp` which look good. I was unable to run the full automated test suite right now, but I can look at doing at later if needed.

Here is the output from the automated test I did run:

https://gist.github.com/cbuto/13dd83b40d29503288b11192ee2c4149

### CODE REVIEW

File: modules/files/files.go [hunk 1]
```diff
@@ -24,6 +24,16 @@ func FileExistsE(path string) (bool, error) {
 	return err == nil, nil
 }
 
+// DirExistsE returns true if the given file exists
```
Comment (brikis98) [inline modules/files/files.go:27]:
```suggestion
// DirExistsE returns true if the given directory exists
```

Comment (brikis98) [reply modules/files/files.go:27]: Actually, this method doesn't seem to check if the given `path` is a directory or not... So it seems to be identical to `FileExistsE` above?

File: modules/files/files.go [hunk 2]
```diff
@@ -74,6 +84,11 @@ func CopyTerragruntFolderToTemp(folderPath string, tempFolderPrefix string) (str
 // CopyFolderToTemp creates a copy of the given folder and all its filtered contents in a temp folder
 // with a unique name and the given prefix.
 func CopyFolderToTemp(folderPath string, tempFolderPrefix string, filter func(path string) bool) (string, error) {
+	_, err := DirExistsE(folderPath)
```
Comment (brikis98) [inline modules/files/files.go:87]: Shouldn't you be storing the boolean returned here and checking it?

File: modules/files/files_test.go [hunk 3]
```diff
@@ -24,6 +24,21 @@ func TestFileExists(t *testing.T) {
...
 }
 
+func TestDirExistsE(t *testing.T) {
+	t.Parallel()
+
+	expectedError := new(os.PathError)
+	currentFile, err := filepath.Abs(os.Args[0])
+	require.NoError(t, err)
+
+	exists1, err := DirExistsE(currentFile)
```
Comment (brikis98) [inline modules/files/files_test.go:34]: Will `os.Args[0]` be the path to the executable (file) or a directory? If it's a file, this check doesn't make much sense...

File: modules/files/files_test.go [hunk 4]
```diff
@@ -48,6 +63,27 @@ func TestIsExistingDir(t *testing.T) {
...
+
+	currentFileDir := filepath.Dir(currentFile)
+	filter := func(path string) bool {
+		return !PathContainsHiddenFileOrFolder(path) && !PathContainsTerraformState(path)
+	}
+
+	_, err = CopyFolderToTemp("/not/a/real/path", tempFolderPrefix, filter)
+	assert.IsType(t, expectedErrorType, err)
+
+	folder, err := CopyFolderToTemp(currentFileDir, tempFolderPrefix, filter)
```
Comment (brikis98) [inline modules/files/files_test.go:82]: We shouldn't copy anything to the current working dir, as that will leave the file system in a messy state. You can use `ioutil.TempDir` to create a dir in the system temp folder. 

Also, the checks in this test don't seem to work. One check is that `CopyFolderToTemp` handles in valid paths correctly, which is fine. But shouldn't the other check, the one related to this PR, be that it _doesn't_ overwrite an existing folder?

File: modules/test-structure/test_structure.go [hunk 5]
```diff
@@ -72,6 +72,13 @@ func CopyTerraformFolderToTemp(t testing.TestingT, rootFolder string, terraformM
 		return filepath.Join(rootFolder, terraformModuleFolder)
 	}
 
+	fullTerraformModuleFolder := filepath.Join(rootFolder, terraformModuleFolder)
+
+	_, err := files.DirExistsE(fullTerraformModuleFolder)
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (brikis98) [inline modules/test-structure/test_structure.go:80]: Same issue here... Shouldn't you be using the bool returned?

**Review by brikis98 — COMMENTED** [review]
Thanks for the PR!

File: modules/files/files.go (hunk 1 above)
Comment (cbuto) [reply modules/files/files.go]: yeah...😅 I removed this function and used `FileExistsE` instead. At first i created it so i could return an error for a directory not existing instead of just the bool.

File: modules/files/files.go (hunk 2 above)
Comment (cbuto) [reply modules/files/files.go]: fixed to use the bool from FileExistsE

File: modules/files/files_test.go (hunk 3 above)
Comment (cbuto) [reply modules/files/files_test.go]: I removed this test and method

File: modules/files/files_test.go (hunk 4 above)
Comment (cbuto) [reply modules/files/files_test.go]: Update to use a temp dir and also fixed the checks to cover what you described, let me know if those make more sense now!

File: modules/test-structure/test_structure.go (hunk 5 above)
Comment (cbuto) [reply modules/test-structure/test_structure.go]: fixed as well

File: modules/files/files.go [hunk 6]
```diff
@@ -74,6 +74,14 @@ func CopyTerragruntFolderToTemp(folderPath string, tempFolderPrefix string) (str
 // CopyFolderToTemp creates a copy of the given folder and all its filtered contents in a temp folder
 // with a unique name and the given prefix.
 func CopyFolderToTemp(folderPath string, tempFolderPrefix string, filter func(path string) bool) (string, error) {
+	exists, err := FileExistsE(folderPath)
+	if err != nil {
+		return "", err
+	}
+	if !exists {
+		return "", os.ErrNotExist
```
Comment (brikis98) [inline modules/files/files.go:82]: NIT: Could you create a new error that includes the path of the non-existent folder in the error message? That'll help quite a bit with debugging.

File: modules/files/files_test.go [hunk 7]
```diff
@@ -48,6 +48,27 @@ func TestIsExistingDir(t *testing.T) {
...
+	require.NoError(t, err)
+
+	filter := func(path string) bool {
+		return !PathContainsHiddenFileOrFolder(path) && !PathContainsTerraformState(path)
+	}
+
+	folder, err := CopyFolderToTemp("/not/a/real/path", tempFolderPrefix, filter)
+	require.Error(t, err)
+	exists := FileExists(folder)
+	assert.False(t, exists)
```
Comment (brikis98) [inline modules/files/files_test.go:65]: NIT:

```suggestion
	assert.False(t, FileExists(folder))
```

File: modules/files/files_test.go [hunk 8]
```diff
@@ -48,6 +48,27 @@ func TestIsExistingDir(t *testing.T) {
...
+
+	folder, err = CopyFolderToTemp(tmpDir, tempFolderPrefix, filter)
+	assert.DirExists(t, folder)
+	assert.Nil(t, err)
```
Comment (brikis98) [inline modules/files/files_test.go:69]:
```suggestion
	assert.NoError(t, err)
```

File: modules/test-structure/test_structure.go [hunk 9]
```diff
@@ -72,6 +72,16 @@ func CopyTerraformFolderToTemp(t testing.TestingT, rootFolder string, terraformM
 		return filepath.Join(rootFolder, terraformModuleFolder)
 	}
 
+	fullTerraformModuleFolder := filepath.Join(rootFolder, terraformModuleFolder)
+
+	exists, err := files.FileExistsE(fullTerraformModuleFolder)
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (brikis98) [inline modules/test-structure/test_structure.go:80]:
```suggestion
	require.NoError(t, err)
```

File: modules/test-structure/test_structure.go [hunk 10]
```diff
@@ -72,6 +72,16 @@ func CopyTerraformFolderToTemp(t testing.TestingT, rootFolder string, terraformM
...
+	if !exists {
+		t.Fatal(os.ErrNotExist, fullTerraformModuleFolder)
```
Comment (brikis98) [inline modules/test-structure/test_structure.go:82]: Will this show a clear error message?

Comment (cbuto) [reply modules/test-structure/test_structure.go:82]: This will result in: 

`TestTerraformAwsExamplePlan: test_structure.go:82: file does not exist ../no/examples/terraform-aws-example`

File: modules/files/files_test.go (hunk 7 above)
Comment (cbuto) [reply modules/files/files_test.go]: 👍  fixed

File: modules/test-structure/test_structure.go (hunk 9 above)
Comment (cbuto) [reply modules/test-structure/test_structure.go]: fixed!

File: modules/files/files_test.go (hunk 8 above)
Comment (cbuto) [reply modules/files/files_test.go]: done!

File: modules/files/files.go (hunk 6 above)
Comment (cbuto) [reply modules/files/files.go]: fixed this to include the folderPath. I wonder if I should also use that same error message [here](https://github.com/gruntwork-io/terratest/pull/743/files/5ade4a1b1766a64344ef183e05f64fd59147f71b#diff-822ca59b3639b5fce8df6421bcef822e23c19fcab3e497cfc423a9dfbb1e896a)

**Comment by cbuto** [comment]
@brikis98 Thanks for taking the time to review this, I appreciate it!

File: modules/files/files.go (hunk 6 above)
Comment (brikis98) [reply modules/files/files.go]: Yes please! In fact, we typically define a new type that implements the `error` interface (has an `Error()` method), so that (a) you can check if the error you got back was of a specific type, rather than doing string parsing and (b) you can re-use that error type in more than one place.

File: modules/test-structure/test_structure.go (hunk 10 above)
Comment (brikis98) [reply modules/test-structure/test_structure.go:81]: That's decent, but would be slightly better if it said "directory" instead of file. If you extract + reuse the error type as mentioned above, that'll do the trick.

File: modules/files/files.go (hunk 6 above)
Comment (cbuto) [reply modules/files/files.go]: got it, I created `DirNotFoundError`. Let me know if that's what you were thinking!

**Review by brikis98 — DISMISSED** [review]
LGTM, thanks! I'll kick off tests now.

**Comment by brikis98** [comment]
Ah, doh, I forgot we have a couple random test failures, and we're working on a fix now: https://github.com/gruntwork-io/terratest/pull/756. Let's get that merged first, and then I can re-run the tests here.

**Comment by cbuto** [comment]
I rebased this PR with master to pull in the test updates

**Comment by brikis98** [comment]
Thanks! I'll re-run tests now.

**Review by brikis98 — APPROVED** [review]
Tests passed! Merging now, thank you!

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.32.1
