### PR TITLE
Fix T12 regression

### LINKED ISSUE #293: Error with passing variables as list of string to terraform commands
Hi!
I am trying to test my **AWS IAC** using terratest.
But whenever I'm trying to pass a list of strings from **terratest** to **terraform**. I'm getting error of wrong syntax from terraform.

Terraform version - Terraform v0.11.11

**some variables i'm using** : 
expectedSecurityGroupNames  := []string {"terratest_eth0_security_group", "terratest_eth1_security_group"}
subnetCidrBlocks     := map[string]string {   "terratest_eth0" : "10.1.1.0/24", "terratest_eth1" : "10.1.2.0/24" }

**this is what getting passed to terraform -** 
Running terraform [apply -input=false -lock=false -auto-approve -var vpc_name=terratest-vpc-XAZAD9 -var enable_dns_support=true -var az=ap-southeast-1c -var subnet_names=[terratest_eth0, terratest_eth1] -var map_public_ip_on_launch={terratest_eth0 = false, terratest_eth1 = false} -var source_dest_check_list=[true, false] -var region=ap-southeast-1 -var profile=default -var vpc_cidr_block=10.1.0.0/16 -var enable_dns_hostnames=true -var subnet_cidr_blocks={terratest_eth0 = 10.1.1.0/24, terratest_eth1 = 10.1.2.0/24} -var security_group_names=[terratest_eth0_security_group, terratest_eth1_security_group] -var private_ips_count_list=[1, 0]]

**This is expected -** 
Running terraform [apply -input=false -lock=false -auto-approve -var vpc_cidr_block="10.1.0.0/16" -var enable_dns_hostnames="true" -var enable_dns_support="true" -var subnet_cidr_blocks={terratest_eth0 = "10.1.1.0/24", terratest_eth1 = "10.1.2.0/24"} -var map_public_ip_on_launch={terratest_eth0 = "false", terratest_eth1 = "false"} -var source_dest_check_list=["true", "false"] -var vpc_name="terratest-vpc-psnigE" -var profile="default" -var az="ap-southeast-1c" -var subnet_names=["terratest_eth0", "terratest_eth1"] -var security_group_names=["terratest_eth0_security_group", "terratest_eth1_security_group"] -var private_ips_count_list=["1", "0"] -var region="ap-southeast-1"]

I'm facing this issue from last week only after few changes in [format.go](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/format.go) file.

**Error I got**  -

invalid value "security_group_names=[terratest_eth0_security_group, terratest_eth1_security_group]" for flag -var: Cannot parse value for variable ("[terratest_eth0_security_group, terratest_eth1_security_group]") as valid HCL: At 1:6: unexpected token while parsing list: IDENT

### PR DESCRIPTION
**Pull request by tonerdo**
This PR addresses the issues introduced by #284. It works by introducing a new `isChild` argument to the `primitiveToHclString` function and creates a special case for the `string` type. If a string is a value in a map or an item in a list then it'll be quoted, otherwise, it remains unquoted. Behaviour for booleans and integers stay the same

E.g.

**Before**
-var name=Instance1
-var subnet_names=[terratest_eth0, terratest_eth1]
-var subnet_cidr_blocks={terratest_eth0 = 10.1.1.0/24, terratest_eth1 = 10.1.2.0/24}
-var private_ips_count_list=[1, 0]

**After**
-var name=Instance1
-var subnet_names=["terratest_eth0", "terratest_eth1"]
-var subnet_cidr_blocks={terratest_eth0 = "10.1.1.0/24", terratest_eth1 = "10.1.2.0/24"}
-var private_ips_count_list=[1, 0]

Fixes #293 

cc @s012sameer @sumitmaggo can you try importing this branch and confirm that this change fixes your issue before I go ahead to merge it

### CODE REVIEW

**Comment by robmorgan** [comment]
I will also update `terraform-google-gke` to use this new version once it's released. It has a couple of nested string maps.

**Comment by yorinasub17** [comment]
FYI, I'll pick this up to add the regression test @tonerdo.

**Comment by yorinasub17** [comment]
UPDATE 91de246 

Added a regression test for the list and map encoding. I verified that this new test fails on `master`, but passes on this branch.

Note that this test fails on terraform 12 due to a bug in output:

```
--- FAIL: TestTerraformBasicExample (2.97s)
    output.go:58: json: cannot unmarshal array into Go value of type map[string]interface {}
FAIL
FAIL    github.com/gruntwork-io/terratest/test  3.007s
```

Looking into the output bug now.

**Comment by yorinasub17** [comment]
Ah this is because the output format changed when using the json type:

TF11
```
{
     "sensitive": false,
     "type": "list",
     "value": [
         "test"
     ]
}
```

TF12
```
["test"]
```

I won't address this in this PR, but filed issue https://github.com/gruntwork-io/terratest/issues/299 to track the bug.

**Comment by s012sameer** [comment]
Hi @tonerdo , these changes worked for me and fixed the issue #293 . Thanks... Are these changes going to be merged with the master branch ?

**Comment by sumitmaggo** [comment]
Thanks @tornedo, the changes work for me, when will the new release be made?

File: modules/terraform/format.go [hunk 1]
```diff
@@ -140,21 +140,22 @@ func mapToHclString(m map[string]interface{}) string {
...
 		}
 		return "0"
 
-	// Note: due to a Terraform bug (https://github.com/hashicorp/terraform/issues/7962), we can't use proper HCL
-	// syntax for ints have to wrap them as strings by falling through to the default case
-	//case int: return strconv.Itoa(v)
+	case string:
+		// If string is a child of a larger data structure (e.g. list of string, map of string), ensure value is quoted
+		if isChild {
+			return fmt.Sprintf("\"%v\"", v)
```
Comment (brikis98) [inline modules/terraform/format.go]: Would it make more sense to do the inverse? That is, wrap _all_ strings, but then in the top-level method, if the value is returned, _unwrap_ the quotes there? That way, you don't have to pass this weird boolean all the way through.

File: examples/terraform-basic-example/variables.tf [hunk 2]
```diff
@@ -26,3 +25,15 @@ variable "example2" {
...
+  description = "An example variable that is a list."
+  type        = "list"
+  default     = []
+}
+
+variable "example_map" {
+  description = "An example variable that is a map."
+  type        = "map"
+  default     = {}
+}
```
Comment (brikis98) [inline examples/terraform-basic-example/variables.tf]: Do we have tests for nested lists and maps?

File: modules/terraform/format.go (hunk 1 above)
Comment (yorinasub17) [reply modules/terraform/format.go]: IMO, I think this is actually easier to understand from an algorithm perspective. It is much easier to understand mentally in the context of `primitiveToHclString` what to do when nested in a larger structure, than it is to think about what we need to do about what `primitiveToHclString` returns in the context of the top most level, worrying about whether the nested value was a string or bool or int (which we don't know at the top level).

Comment (tonerdo) [reply modules/terraform/format.go]: We could probably rename the parameter to `isNested` to make it clearer

Comment (yorinasub17) [reply modules/terraform/format.go]: I like that name better, so went ahead and did that.

File: examples/terraform-basic-example/variables.tf (hunk 2 above)
Comment (yorinasub17) [reply examples/terraform-basic-example/variables.tf]: Attempted to add some nested lists / maps testing: 6d1e95d .

**Comment by yorinasub17** [comment]
> And are we running tests now against both TF 11 and 12?

Not yet. AFAIK, there are two things we need to do to be able to start testing on tf12:

- We need to update the examples to be tf12 compatible.
- https://github.com/gruntwork-io/terratest/issues/299

**Comment by brikis98** [comment]
OK, so just to confirm:

1. We've manually tested this with TF11 and TF12 and it works.
1. We have automated tests in the CI job for TF11. We'll add TF12 later, when we update the examples.

Is that right? If so, anything blocking merge and release?

**Comment by yorinasub17** [comment]
> so just to confirm:

Yes that's right.

> If so, anything blocking merge and release?

Nope! Will ship!

**Comment by yorinasub17** [comment]
Thanks for checking in and the thorough review!

**Comment by yorinasub17** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.15.8
