### PR TITLE
Fix shell output log formatting.

### LINKED ISSUE #982: Shell command module logs lines as format strings
Seen in Kuma tests, which use terratest with gingo:

```
Test Multizone Resilience for K8s should see global entities in zone after a global restart 2021-09-03T09:09:21+10:00 retry.go:91: install yaml resource
Test Multizone Resilience for K8s should see global entities in zone after a global restart 2021-09-03T09:09:21+10:00 logger.go:66: Running command kubectl with args [--kubeconfig /home/jpeach/.kube/kind-kuma-1-config apply -f /tmp/Test%20Multizone%20Resilience%20for%20K8s%20should%20see%20global%20entities%20in%20zone%20after%20a%20global%20restart167549003]
Test Multizone Resilience for K8s should see global entities in zone after a global restart 2021-09-03T09:09:21+10:00 logger.go:66: Error from server (InternalError): error when creating "/tmp/Test%!M(MISSING)ultizone%!R(MISSING)esilience%!f(MISSING)or%!K(MISSING)8s%!s(MISSING)hould%!s(MISSING)ee%!g(MISSING)lobal%!e(MISSING)ntities%!i(MISSING)n%!z(MISSING)one%!a(MISSING)fter%!a(MISSING)%!g(MISSING)lobal%!r(MISSING)estart167549003": Internal error occurred: failed calling webhook "mesh.defaulter.kuma-admission.kuma.io": Post "https://kuma-control-plane.kuma-system.svc:443/default-kuma-io-v1alpha1-mesh?timeout=10s": dial tcp 10.96.184.11:443: connect: connection refused
Test Multizone Resilience for K8s should see global entities in zone after a global restart 2021-09-03T09:09:21+10:00 retry.go:103: install yaml resource returned an error: error while running command: exit status 1; Error from server (InternalError): error when creating "/tmp/Test%20Multizone%20Resilience%20for%20K8s%20should%20see%20global%20entities%20in%20zone%20after%20a%20global%20restart167549003": Internal error occurred: failed calling webhook "mesh.defaulter.kuma-admission.kuma.io": Post "https://kuma-control-plane.kuma-system.svc:443/default-kuma-io-v1alpha1-mesh?timeout=10s": dial tcp 10.96.184.11:443: connect: connection refused. Sleeping for 3s and will try again.
```
Note the 3rd log line, where the format string interpolation fails.

The problem is here:

https://github.com/gruntwork-io/terratest/blob/eca92144b6fc75ff55d42214a9b6ddef9345914c/modules/shell/command.go#L179

### PR DESCRIPTION
**Pull request by jpeach**
This fixes #982.

Signed-off-by: James Peach <jpeach@apache.org>

### CODE REVIEW

File: modules/shell/command.go [hunk 1]
```diff
@@ -176,7 +176,7 @@ func readData(t testing.TestingT, log *logger.Logger, reader *bufio.Reader, writ
 			break
 		}
 
-		log.Logf(t, line)
+		log.Logf(t, "%s", line)
```
Comment (brikis98) [inline modules/shell/command.go:179]: Just to make sure I understand:

1. In #982, you show an example where the log output contains what looks like broken string interpolation. I can't see any reason you'd expect interpolation to work, so I'm guessing the real goal is to _disable_ interpolation, so that random `%xxx` style codes in stdout/stderr don't accidentally get interpreted as interpolation, right?
2. If so, wouldn't switching to `log.Log` instead of `log.Logf` be the proper fix here?

**Review by brikis98 — COMMENTED** [review]
Thanks for the PR!

File: modules/shell/command.go (hunk 1 above)
Comment (jpeach) [reply modules/shell/command.go:179]: > 2\. If so, wouldn't switching to `log.Log` instead of `log.Logf` be the proper fix here?

Yeh, I also assumed that at first, but `logging.Logger` only has `Logf`.

Comment (brikis98) [reply modules/shell/command.go:179]: Ah, OK, got it. In that case, could you add a comment above this line explaining:

1. Why we need this "%s" indirection (there's only Logf, no Log)
1. Pointing back to this PR so maintainers know what issue this is fixing.

Thanks!

Comment (jpeach) [reply modules/shell/command.go:185]: Done.

Comment (brikis98) [reply modules/shell/command.go:185]: Perfect, thank you!

**Review by brikis98 — APPROVED** [review]
OK, great, this LGTM. I'll kick off tests now 👍

**Comment by brikis98** [comment]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.37.8
